import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Plus_Jakarta_Sans } from "next/font/google";
import NewsLetter from "@/components/NewsLetter";
import NextTopLoader from "nextjs-toploader";
import FloatingContact from "@/components/FloatingContact";
import "leaflet/dist/leaflet.css";
import { Toaster } from "react-hot-toast";

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternates: {
    canonical: "https://homebaba.ca",
  },
};

export const viewport = {
  initialScale: 1.0,
  width: "device-width",
  height: "device-height",
  minimumScale: 1.0,
  maximumScale: 1.0,
  userScalable: "no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className}`}>
        <NextTopLoader color="red" height={3} />
        <Navbar />
        <Toaster position="top-center" />
        {children}
        <FloatingContact />
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
